import Providers from "../../store/provider";
import {Montserrat} from "next/font/google"
import Carrito from "./carrito/Carrito";
import Header from "./header/Header";
import global from "./global.module.css";
import Baner from "./baner/Baner";
import Categorias from "./categorias/Categorias";

const fuente= Montserrat({
  weight: "400",
  subsets:["latin"]
})


export const metadata = {
  title: 'TechVibe.',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <Providers>
        <body  className={`${fuente.className} ${global.body}`}>
          <Header/>
          <Baner/>
      {/*<Carrito/>*/}
          <Categorias/>
           {children}

        </body>
      </Providers>
    </html>
  )
}

