import Providers from "../../store/provider";
import {Montserrat} from "@next/font/google"
import Carrito from "./carrito/Carrito";

const fuente= Montserrat({
  weight: "400",
  subsets:["latin"]
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <Providers>
        <body  className={fuente.className}>
          <Carrito/>
          {children}
        </body>
      </Providers>
    </html>
  )
}

